// Curated source links checked on 2026-09-08. A live link is a channel's radio format,
// not a promise that it is broadcasting now. Never overwrite administrator edits.
const playlist=(slug,title,genre,id,artist,description,tags)=>({slug,title,genre,kind:'playlist',url:'https://www.youtube.com/playlist?list='+id,artist,description,tags});
export const musicSeeds=[
  {slug:'eletronicas-selecao-da-arena',title:'Música eletrônica · seleção da arena',genre:'eletronica',kind:'video',url:'https://www.youtube.com/watch?v=98ovJs-Ibd4',artist:'Seleção enviada à VitrineCity',description:'O mix de música eletrônica escolhido para a estreia da Pulse Arena. Assista ao vídeo completo no player do YouTube dentro da VitrineCity.',tags:'eletronica, dance, mix, festa'},
  playlist('tomorrowland-winter-2026','Tomorrowland Winter 2026 · DJ sets','eletronica','PLoSIOFPSXQoMBTGDqYPiTP7CP_PlxC5jB','Tomorrowland','DJ sets reunidos pelo canal Tomorrowland na edição de inverno de 2026. Uma seleção para conhecer diferentes apresentações de música eletrônica.','festival, dj, winter, dance'),
  playlist('tomorrowland-brasil-2025','Tomorrowland Brasil 2025 · DJ sets','eletronica','PLoSIOFPSXQoMwpfuQrKNGXb30FW5cBYJP','Tomorrowland','Apresentações da edição brasileira de 2025 reunidas pelo próprio canal do festival. Abra a playlist para escolher os sets disponíveis.','festival, brasil, dj, dance'),
  playlist('sertanejo-sofrencia','Sertanejo Sofrência · seleção Som Livre','sertanejo','PLxFfose56Ajdhx7zxpJNjn-8w-9wPMFLL','Som Livre','Uma seleção de sertanejo romântico e sofrência publicada pela Som Livre. Explore os vídeos da playlist e escolha a trilha para seu momento.','romantico, sofrencia, sertaneja'),
  playlist('ze-neto-cristiano','Zé Neto & Cristiano · Só as melhores','sertanejo','PLxFfose56Ajc0-Vstk5iyX1ua-eNSytr1','Som Livre','Playlist da Som Livre dedicada a Zé Neto & Cristiano, com músicas da dupla reunidas em uma só seleção.','ze neto, cristiano, sertanejo universitario'),
  playlist('varanda-sertanejeiro-barretos','Varanda do Sertanejeiro · Barretos 2025','sertanejo','PLxFfose56AjcA2KrpDxklLWEZXDQ8_Vgo','Som Livre','Apresentações do Rancho do Sertanejeiro em Barretos, na edição de 2025. São registros de shows para assistir quando quiser.','barretos, rancho, acustico, shows'),
  playlist('forro-daquele-jeito','Forró Daquele Jeito','forro','PLxFfose56AjdIJKPjkjVdUL7ngaQszBuW','Som Livre','Seleção de forró com Mari Fernandez, Raí Saia Rodada, Dorgival Dantas e Felipe Amorim, publicada no canal Som Livre.','mari fernandez, rai saia rodada, dorgival dantas, felipe amorim'),
  playlist('sorriso-maroto','O melhor do Sorriso Maroto','pagode','PLxFfose56AjdVQii7U1yc0Eyd-9Rt6QXW','Som Livre','Canções do Sorriso Maroto em uma playlist da Som Livre. Um espaço para quem procura pagode, romance e músicas para cantar junto.','sorriso maroto, pagode, samba, romantico'),
  playlist('festa-pop-nacional','Festa Pop · hits nacionais','pop','PLxFfose56AjdM9dIfwNAP4mGww0r1acU0','Som Livre','Hits do pop nacional selecionados pela Som Livre na playlist Festa Pop 2025. Descubra as faixas e os artistas disponíveis no player.','pop nacional, festa, brasil'),
  playlist('tim-maia','Tim Maia · Só as melhores','mpb','PLxFfose56AjcCX4-DwfWdy2j125J0P1vT','Som Livre','Uma playlist da Som Livre dedicada a Tim Maia. Soul e música brasileira reunidos para acompanhar sua pausa na cidade.','tim maia, soul, mpb, musica brasileira'),
  playlist('filipe-ret','Filipe Ret · Rap da Lealdade','rap','PLxFfose56AjfE-VH7VF0DRzLlIeJ2vmjH','Som Livre','Faixas de Filipe Ret reunidas pela Som Livre na seleção Rap da Lealdade. Explore os vídeos disponíveis e acompanhe o repertório.','filipe ret, rap, hip hop'),
  {slug:'radio-deep-melodic-house',title:'Deep & Melodic House · rádio Monstercat',genre:'eletronica',kind:'live',url:'https://www.youtube.com/watch?v=WsDyRAPFBC8',artist:'Monstercat Silk',description:'Rádio apresentada pela Monstercat Silk como uma seleção contínua de deep e melodic house, voltada a relaxar e estudar. O player informa se a transmissão está disponível.',tags:'deep house, melodic house, relaxar, estudar, radio, 24 horas'},
  {slug:'radio-progressive-house',title:'Progressive House · rádio Monstercat',genre:'eletronica',kind:'live',url:'https://www.youtube.com/watch?v=d8Oc90QevaI',artist:'Monstercat Silk',description:'Rádio de progressive house indicada pela Monstercat Silk para acompanhar o dia com música eletrônica. A continuidade depende da transmissão mantida pelo canal.',tags:'progressive house, foco, energia, radio, 24 horas'}
];
