// Original editorial collection, version 1. Keep its order stable: dated share
// links refer to this 31-day cycle, anchored to the collection's launch date.
export const PRAYER_COLLECTION_START = '2026-09-10';
export const PRAYER_TIME_ZONE = 'America/Sao_Paulo';

const entries = [
  ['Um coração mais tranquilo', 'Senhor Jesus, acolhe meu coração neste dia.', 'Quando a preocupação ocupar meus pensamentos, ajuda-me a reconhecer o que está ao meu alcance. Dá-me serenidade para respirar, organizar uma tarefa de cada vez e aceitar que nem tudo precisa ser resolvido agora.', 'Cuida de quem atravessa dias difíceis. Ensina-nos a escutar sem pressa, a pedir ajuda quando for preciso e a oferecer companhia. Que minhas palavras sejam cuidadosas e minhas escolhas abram espaço para a paz.', 'Um passo de cada vez', 'Uma pausa pode ajudar a perceber o próximo passo possível. Não é preciso carregar sozinho tudo o que preocupa você.', 'Qual tarefa pequena pode receber sua atenção agora?'],
  ['Gratidão pelas pequenas coisas', 'Senhor, quero olhar este dia com atenção e gratidão.', 'Ajuda-me a perceber o alimento, o abrigo, uma conversa e cada gesto de cuidado que tantas vezes passam despercebidos. Que eu reconheça o esforço das pessoas que tornam minha vida possível, sem esquecer quem ainda precisa de apoio.', 'Quando houver tristeza, não me deixes fingir que ela não existe. Ensina-me a acolher meus sentimentos e, junto deles, guardar uma lembrança boa. Que a gratidão me torne mais generoso e presente na vida de alguém.', 'Reparar no que sustenta', 'A gratidão pode conviver com um dia difícil. Ela não exige alegria constante: começa ao reconhecer um cuidado real.', 'A quem você pode agradecer por um gesto concreto?'],
  ['Coragem para recomeçar', 'Jesus, acompanha-me quando eu precisar começar de novo.', 'Ajuda-me a olhar meus erros com honestidade, sem transformar uma falha em toda a minha história. Dá-me disposição para reparar o que for possível, aprender com o caminho e buscar orientação antes de dar o próximo passo.', 'Que eu encontre coragem nas atitudes pequenas e constância nas escolhas de hoje. Aproxima de mim pessoas com quem eu possa conversar com confiança. Ensina-me também a acolher quem está tentando recomeçar ao meu lado.', 'Recomeçar também é aprender', 'Um recomeço pode ser discreto: pedir desculpas, reorganizar um plano ou retomar um cuidado que ficou para depois.', 'Qual começo pequeno cabe no seu dia?'],
  ['Cuidado com a família', 'Senhor, entrego em oração as pessoas que chamo de família.', 'Acolhe os lares que vivem alegria e aqueles que enfrentam conflitos ou distância. Ajuda-nos a conversar com respeito, reconhecer limites e repartir responsabilidades. Que o carinho apareça também nas tarefas simples e na atenção de cada dia.', 'Dá-nos humildade para pedir desculpas e sabedoria para buscar apoio quando uma situação nos fizer mal. Que nossas relações sejam lugar de dignidade e cuidado, e que ninguém precise suportar a dor em silêncio para se sentir pertencente.', 'Carinho que se torna atitude', 'Uma relação se fortalece com escuta, respeito e limites. Um gesto simples de atenção pode abrir uma conversa importante.', 'Que gesto de cuidado você pode oferecer sem ultrapassar seus limites?'],
  ['Esperança em dias incertos', 'Jesus, permanece comigo diante do que ainda não sei.', 'Quando eu quiser encontrar todas as respostas de uma vez, ajuda-me a reconhecer meus limites. Dá-me clareza para procurar informações confiáveis, conversar com quem pode orientar e cuidar das decisões que de fato dependem de mim.', 'Que a incerteza não me impeça de viver os encontros de hoje. Sustenta minha esperança sem me afastar da realidade. Ensina-me a caminhar com prudência, a mudar de plano quando necessário e a acolher ajuda com gratidão.', 'Cuidar do que é possível', 'Não conhecer o amanhã pode ser difícil. Hoje, escolha uma ação concreta que ajude você a se sentir acompanhado e orientado.', 'Quem pode ajudar você a pensar no próximo passo?'],
  ['Descanso para a alma', 'Senhor, recebe o cansaço que trago comigo.', 'Ajuda-me a perceber quando preciso parar. Que eu não meça meu valor apenas pelo que produzo ou resolvo. Dá-me liberdade para descansar, organizar minhas responsabilidades e repartir o peso que se tornou grande demais.', 'Cuida de quem trabalha muito e de quem cuida de outras pessoas. Que encontremos tempo, apoio e condições para recuperar as forças. Ensina-me a oferecer descanso também ao outro, com compreensão e ajuda possível.', 'Descansar é um cuidado', 'Seu valor não depende de estar disponível o tempo todo. Uma pausa e uma conversa sobre responsabilidades também fazem parte do cuidado.', 'Qual pausa possível você pode reservar para hoje?'],
  ['Gentileza nas palavras', 'Jesus, ajuda-me a falar com verdade e delicadeza.', 'Antes de responder com pressa, ensina-me a escutar. Que eu procure compreender sem humilhar, discordar sem ferir e reconhecer quando minhas palavras precisam ser reparadas. Dá-me atenção ao que a outra pessoa consegue expressar.', 'Livra-me da vontade de espalhar aquilo que não verifiquei. Que minhas conversas tragam respeito, mesmo nas diferenças. E, quando for necessário dizer não, ajuda-me a fazê-lo com firmeza, protegendo minha dignidade e a de quem está comigo.', 'Escutar antes de responder', 'Gentileza não impede uma conversa firme. Ela ajuda a tratar uma diferença sem diminuir a outra pessoa.', 'Em qual conversa você pode dar mais espaço à escuta?'],
  ['Companhia para quem está só', 'Senhor, lembra-me de quem sente falta de companhia.', 'Acolhe os momentos de solidão e o desejo de ser ouvido. Ajuda-nos a construir encontros respeitosos, a procurar pessoas de confiança e a aceitar convites que nos façam bem. Que cada pessoa seja tratada como alguém que importa.', 'Desperta em mim a atenção para quem ficou distante. Dá-me sensibilidade para oferecer presença sem invadir, e coragem para dizer quando eu também precisar conversar. Que encontremos apoio em laços reais e no cuidado de cada dia.', 'Presença sem pressa', 'Uma mensagem atenciosa pode abrir espaço para uma conversa. Também é válido ser a pessoa que pede companhia.', 'Com quem você gostaria de conversar hoje?'],
  ['Sabedoria nas escolhas', 'Jesus, ilumina minhas escolhas com prudência e honestidade.', 'Quando eu estiver diante de uma decisão, ajuda-me a compreender suas consequências e a ouvir bons conselhos. Que eu não aja apenas por medo, pressão ou promessa fácil. Dá-me tempo para verificar o que ainda não conheço.', 'Ensina-me a considerar as pessoas afetadas pelo que faço. Que meus caminhos respeitem a vida, a dignidade e meus próprios limites. Se eu perceber um erro, dá-me humildade para corrigir a direção e seguir aprendendo.', 'Uma decisão com cuidado', 'Decisões importantes merecem informação e tempo. Buscar orientação é uma forma de responsabilidade.', 'O que você precisa compreender melhor antes de decidir?'],
  ['Paciência com o caminho', 'Senhor, ensina-me a viver o tempo das coisas.', 'Quando a espera me inquietar, ajuda-me a distinguir o que pede ação daquilo que precisa de tempo. Que eu possa acompanhar meus planos com atenção, sem tratar cada demora como uma derrota ou me comparar com o percurso de outra pessoa.', 'Dá-me constância para cuidar do que comecei e flexibilidade para reconhecer mudanças. Que eu celebre os avanços pequenos e aprenda a conversar sobre minhas dificuldades. Sustenta em mim a paciência que caminha, observa e procura apoio.', 'Reconhecer os pequenos avanços', 'Nem todo avanço aparece depressa. Vale observar o que você aprendeu e o cuidado que já conseguiu manter.', 'Que pequeno progresso você pode reconhecer em si?'],
  ['Acolhimento na saudade', 'Jesus, acolhe a saudade que hoje visita meu coração.', 'Recebe as lembranças de quem está longe e de quem já não pode estar conosco. Ajuda-me a viver a falta sem exigir de mim uma força que não tenho. Que eu encontre pessoas com quem possa falar, lembrar e também ficar em silêncio.', 'Dá-me liberdade para sorrir ao recordar e para chorar quando for preciso. Que o amor vivido inspire meus gestos de cuidado no presente. Acompanha cada família que atravessa uma perda e precisa de tempo, presença e apoio.', 'Lembrar no seu tempo', 'A saudade não segue um calendário igual para todos. Uma lembrança pode ser acolhida com carinho, sem pressa para mudar o que você sente.', 'Qual lembrança você gostaria de guardar ou compartilhar?'],
  ['Dignidade no trabalho', 'Senhor, acompanha quem trabalha e quem procura uma oportunidade.', 'Ajuda-nos a exercer nossas tarefas com responsabilidade e a reconhecer o valor de cada pessoa. Que o respeito esteja presente nas relações, nos horários e na divisão do esforço. Dá-nos coragem para buscar condições justas e pedir orientação.', 'Acolhe quem enfrenta preocupação com o sustento. Que encontre apoio, informação e oportunidades reais. Ensina-me a agir com honestidade e solidariedade, sem prometer caminhos fáceis. Que o trabalho sirva à vida e não apague o cuidado com ela.', 'Trabalho com respeito', 'Reconhecer o trabalho de alguém pode começar por uma atitude justa e uma palavra específica de agradecimento.', 'Quem merece ter seu esforço reconhecido hoje?'],
  ['Generosidade que respeita', 'Jesus, ensina-me a partilhar com liberdade e cuidado.', 'Ajuda-me a reconhecer o que posso oferecer: tempo, atenção, conhecimento ou ajuda prática. Que meu gesto não humilhe quem recebe e não espere recompensa. Dá-me sensibilidade para perguntar do que a outra pessoa realmente precisa.', 'Lembra-me de cuidar também dos meus limites e das minhas responsabilidades. Que ninguém se sinta obrigado a dar o que não pode. Ensina-nos a construir uma comunidade em que pedir ajuda seja acolhido com respeito e responder seja uma escolha sincera.', 'Ajuda possível, cuidado real', 'Uma contribuição pode ser escuta, companhia ou uma tarefa compartilhada. O cuidado não se mede pelo valor de um pagamento.', 'Qual ajuda possível seria útil para alguém próximo?'],
  ['Humildade para aprender', 'Senhor, abre meu coração para continuar aprendendo.', 'Ajuda-me a reconhecer quando não sei e a fazer perguntas sem vergonha. Que eu encontre pessoas pacientes para ensinar e tenha atenção para distinguir uma informação confiável de uma resposta apressada. Dá-me disposição para praticar aos poucos.', 'Quando eu tiver a oportunidade de ensinar, que não diminua quem está começando. Lembra-me das dificuldades que também já vivi. Que o conhecimento se torne uma ponte entre as pessoas e uma forma de cuidar melhor da vida.', 'Aprender sem se diminuir', 'Perguntar não reduz sua capacidade. Cada pessoa aprende em um ritmo e merece orientação respeitosa.', 'O que você gostaria de aprender com calma?'],
  ['Um olhar de compaixão', 'Jesus, ajuda-me a enxergar as pessoas além da primeira impressão.', 'Antes de julgar uma dificuldade, dá-me disposição para escutar. Que eu não transforme a dor de alguém em comentário ou rótulo. Ensina-me a oferecer apoio com respeito, sem presumir que conheço toda a sua história.', 'Que a compaixão chegue também ao modo como trato a mim mesmo. Ajuda-me a reconhecer minhas limitações e a buscar ajuda sem culpa. Dá-nos coragem para cuidar uns dos outros com atitudes possíveis e responsabilidade.', 'Cada pessoa tem uma história', 'Escutar com atenção pode mudar o modo como entendemos uma situação. Não é necessário ter uma resposta para oferecer presença.', 'Como você pode escutar alguém sem tentar resolver tudo?'],
  ['Cuidado com a criação', 'Senhor, agradeço pela vida que floresce ao nosso redor.', 'Ensina-me a cuidar da água, da terra e dos lugares que compartilhamos. Que eu perceba a beleza de uma árvore, o alimento que chega à mesa e o trabalho de quem cultiva. Ajuda-me a transformar gratidão em atenção e responsabilidade.', 'Dá-nos sabedoria para evitar desperdícios e aprender formas adequadas de cuidar das plantas e dos animais. Que nossos gestos considerem também quem virá depois de nós. Faz crescer em mim o respeito por toda a criação.', 'Um gesto pelo lugar onde vivemos', 'O cuidado com o ambiente pode começar por um hábito possível, aprendido com atenção e mantido aos poucos.', 'Que desperdício você pode reduzir hoje?'],
  ['Respeito entre gerações', 'Jesus, aproxima nossos caminhos com escuta e respeito.', 'Ajuda-nos a valorizar quem viveu outras experiências e quem está descobrindo o mundo agora. Que a idade não seja motivo para diminuir ninguém. Dá-nos paciência para explicar, liberdade para perguntar e curiosidade para aprender uns com os outros.', 'Cuida das pessoas que precisam de apoio para realizar tarefas do dia. Que recebam ajuda sem perder sua voz e suas escolhas. Ensina-me a oferecer presença e a reconhecer a história, os desejos e a dignidade de cada pessoa.', 'Ajuda que preserva a escolha', 'Oferecer apoio começa por perguntar se ele é desejado. Fazer junto pode ser mais acolhedor do que decidir pelo outro.', 'O que você pode aprender com alguém de outra geração?'],
  ['Responsabilidade ao compartilhar', 'Senhor, guia também aquilo que leio e compartilho.', 'Quando uma mensagem despertar medo ou entusiasmo, ajuda-me a fazer uma pausa e verificar sua origem. Que eu não espalhe boatos, exponha a intimidade de alguém ou use a fé para pressionar outras pessoas. Dá-me cuidado com a confiança de quem me escuta.', 'Que as palavras que envio levem acolhimento e informação responsável. Ensina-me a reconhecer um engano e a corrigi-lo com clareza. Que eu saiba desligar a tela para estar presente quando alguém precisar de minha atenção.', 'Uma pausa antes de encaminhar', 'Mensagens de carinho não precisam de ameaças nem promessas de recompensa. Verificar uma informação é um gesto de respeito.', 'A mensagem que você quer compartilhar tem uma origem confiável?'],
  ['Força para pedir ajuda', 'Jesus, acompanha-me quando eu não conseguir seguir sozinho.', 'Ajuda-me a reconhecer minhas necessidades e a procurar alguém de confiança. Que eu possa falar com clareza sobre o que está difícil, sem acreditar que pedir apoio é fraqueza. Dá-me coragem para buscar orientação adequada quando precisar.', 'Acolhe também quem escuta e cuida. Que haja respeito pelos limites de todos e espaço para repartir responsabilidades. Ensina-nos a unir oração e cuidado concreto, valorizando as pessoas e os serviços que podem oferecer ajuda.', 'Você pode procurar apoio', 'Uma conversa com alguém de confiança pode ser um começo. A oração pode acompanhar o cuidado necessário em cada situação.', 'Quem pode ouvir você com respeito hoje?'],
  ['Paz nas diferenças', 'Senhor, ajuda-nos a conviver sem abrir mão do respeito.', 'Quando houver opiniões diferentes, ensina-me a conversar com clareza e a escutar sem insultar. Que eu não confunda discordância com falta de dignidade. Dá-me firmeza para defender o cuidado com a vida e humildade para rever minhas certezas.', 'Que nossas relações tenham espaço para limites e para acordos possíveis. Afasta de mim a vontade de vencer uma conversa a qualquer custo. Ensina-nos a buscar caminhos honestos, em que a paz seja construída por atitudes de respeito.', 'Discordar com dignidade', 'Uma conversa pode precisar de pausa. Respeitar limites ajuda a tratar as diferenças com mais clareza.', 'Que limite pode tornar uma conversa mais respeitosa?'],
  ['Alegria sem comparação', 'Jesus, ajuda-me a acolher as alegrias simples de hoje.', 'Que eu não meça minha vida apenas pelas conquistas que vejo nos outros. Ensina-me a reconhecer meu percurso, meus vínculos e os momentos em que posso descansar ou sorrir. Dá-me um olhar atento para aquilo que é verdadeiro em minha rotina.', 'Quando alguém celebrar uma conquista, que eu possa me alegrar sem diminuir meus próprios passos. E, se este for um dia difícil, ajuda-me a não exigir felicidade de mim. Que eu encontre acolhimento para viver cada sentimento com honestidade.', 'Seu caminho merece respeito', 'A vida mostrada por outras pessoas não conta toda a história delas. Seu ritmo e suas necessidades também importam.', 'Que momento simples trouxe algum conforto ao seu dia?'],
  ['Presença no dia de hoje', 'Senhor, ajuda-me a estar presente no que vivo agora.', 'Quando meus pensamentos correrem para muitas preocupações, lembra-me de voltar com calma ao encontro e à tarefa diante de mim. Que eu escute quem fala, perceba meu cansaço e dê atenção às necessidades que consigo reconhecer.', 'Ensina-me a fazer planos sem perder os pequenos momentos do presente. Dá-me liberdade para guardar a tela, respirar e olhar ao redor. Que eu encontre no dia de hoje oportunidades de aprender, cuidar e receber carinho.', 'Um encontro de cada vez', 'Estar presente pode começar ao dedicar alguns minutos inteiros a uma pessoa ou a uma tarefa.', 'A quem ou a quê você quer oferecer atenção agora?'],
  ['Honestidade no caminho', 'Jesus, fortalece em mim o desejo de agir com honestidade.', 'Que minhas palavras correspondam ao que posso cumprir. Ajuda-me a reconhecer um erro sem escondê-lo, a tratar compromissos com cuidado e a não aproveitar a dificuldade de outra pessoa. Dá-me coragem para escolher o que é justo nas situações pequenas.', 'Quando houver dúvida, ensina-me a procurar orientação e a conferir os fatos. Que minha fé apareça no respeito com que vivo e negocio. Sustenta minha disposição para reparar danos e construir confiança com atitudes constantes.', 'Confiança se constrói em gestos', 'Uma promessa responsável considera o que realmente pode ser feito. Reconhecer um limite também é agir com verdade.', 'Qual compromisso precisa de uma conversa honesta hoje?'],
  ['Acolher as mudanças', 'Senhor, caminha comigo quando a vida mudar de direção.', 'Acolhe o receio de deixar uma rotina conhecida e a saudade do que ficou para trás. Ajuda-me a compreender o novo cenário, buscar informação e fazer ajustes aos poucos. Que eu encontre apoio sem precisar fingir que a mudança é simples.', 'Dá-me coragem para aprender e serenidade para reconhecer o que permanece importante. Que eu cuide dos vínculos, do descanso e das escolhas possíveis. Ensina-me a receber uma etapa nova com prudência e espaço para a esperança.', 'Adaptar-se pode levar tempo', 'Uma mudança pede aprendizado. Você pode dividir o que precisa fazer em partes e procurar companhia nesse processo.', 'Que apoio tornaria esta mudança um pouco mais possível?'],
  ['Cuidado com quem cuida', 'Jesus, acolhe as pessoas que dedicam seus dias a cuidar.', 'Lembra-nos de que quem oferece apoio também sente cansaço e precisa ser ouvido. Ajuda-nos a dividir tarefas, reconhecer o esforço e buscar orientação adequada. Que o cuidado não dependa do sacrifício silencioso de uma única pessoa.', 'Dá-me sensibilidade para oferecer ajuda concreta e respeito para perguntar o que é necessário. Que haja espaço para descanso, conversa e vida própria. Sustenta nossos laços com responsabilidade e carinho, valorizando cada pessoa envolvida.', 'Repartir também é cuidar', 'Perguntar por uma tarefa específica pode tornar sua ajuda mais útil. Quem cuida merece tempo para si.', 'Qual responsabilidade você pode ajudar a repartir?'],
  ['Reconciliação com respeito', 'Senhor, orienta-me quando eu precisar reparar uma relação.', 'Ajuda-me a reconhecer o que fiz e a pedir desculpas sem exigir uma resposta imediata. Que eu compreenda que a confiança precisa de atitudes e tempo. Dá-me disposição para escutar e mudar o que está ao meu alcance.', 'Ensina-me também a respeitar limites e a buscar apoio diante de situações que machucam. Que o desejo de paz não me obrigue a aceitar violência ou humilhação. Guia-nos para caminhos de dignidade, responsabilidade e cuidado.', 'Reparar exige atitude', 'Um pedido de desculpas não impõe reconciliação. Respeitar o tempo e os limites do outro também faz parte da reparação.', 'Qual atitude concreta pode acompanhar um pedido de desculpas?'],
  ['Amizades que acolhem', 'Jesus, agradeço pelas amizades que tornam a vida mais acompanhada.', 'Ajuda-me a cultivar laços com sinceridade, atenção e respeito. Que eu saiba celebrar, ouvir uma preocupação e dizer com delicadeza quando não puder estar disponível. Ensina-me a não tratar o carinho como uma dívida.', 'Cuida de quem procura novos vínculos e de quem sente uma amizade distante. Dá-nos coragem para iniciar uma conversa e liberdade para reconhecer relações que nos fazem bem. Que a presença mútua seja escolha, alegria e cuidado.', 'Cultivar sem cobrar', 'Uma amizade pode ser lembrada em uma mensagem simples. Ofereça carinho deixando espaço para o tempo da outra pessoa.', 'Que amizade você gostaria de cultivar com um gesto de atenção?'],
  ['Esperança para a comunidade', 'Senhor, acolhe o lugar onde vivemos e as pessoas ao nosso redor.', 'Ajuda-nos a perceber necessidades que passam despercebidas: uma calçada difícil, alguém sem companhia, uma família precisando de orientação. Que a solidariedade se torne uma ação responsável, feita com respeito e sem expor a história de quem recebe ajuda.', 'Dá-nos disposição para participar, aprender e conversar sobre soluções possíveis. Que ninguém seja tratado como menos importante. Ensina-me a somar meus esforços aos de outras pessoas e a cuidar do espaço que compartilhamos.', 'Pertencer também é participar', 'Uma comunidade se fortalece quando as pessoas são ouvidas. Um gesto possível pode abrir caminho para uma ajuda organizada.', 'Que necessidade do seu entorno merece uma escuta atenta?'],
  ['Serenidade diante dos limites', 'Jesus, ajuda-me a reconhecer meus limites com respeito.', 'Quando eu não puder fazer tudo o que esperam de mim, dá-me clareza para conversar e reorganizar prioridades. Que eu não transforme cansaço em culpa nem prometa aquilo que não consigo cumprir. Ensina-me a cuidar do tempo e das forças que tenho.', 'Ajuda-me a reconhecer também os limites de quem está ao meu lado. Que possamos negociar responsabilidades sem humilhação e pedir ajuda sem vergonha. Sustenta em nós o cuidado que permite continuar com dignidade.', 'Um não também pode cuidar', 'Explicar um limite com respeito ajuda a construir acordos mais honestos. Você não precisa resolver todas as demandas sozinho.', 'Qual limite precisa ser comunicado com calma?'],
  ['Um olhar para o que floresce', 'Senhor, ajuda-me a perceber os cuidados que começam a dar fruto.', 'Que eu reconheça uma habilidade aprendida, uma conversa melhor ou um hábito retomado. Dá-me paciência para continuar sem exigir perfeição. Ensina-me a valorizar os esforços de quem está comigo, inclusive aqueles que quase ninguém vê.', 'Quando algo não acontecer como planejei, ajuda-me a observar, aprender e buscar outro caminho. Que minha esperança se apoie também em atitudes possíveis. Recebe meu desejo de crescer e de contribuir com a vida ao meu redor.', 'Valorizar o processo', 'Um cuidado repetido pode produzir pequenas mudanças. Observe o que ficou mais possível, mesmo que ainda haja dificuldades.', 'Que cuidado você gostaria de continuar cultivando?'],
  ['Encerrar o dia com paz', 'Jesus, recebe este dia com tudo o que ele trouxe.', 'Agradeço pelos encontros e reconheço o que foi difícil. Ajuda-me a olhar minhas escolhas com honestidade, guardar o que aprendi e deixar para amanhã as tarefas que podem esperar. Que eu encontre descanso sem precisar ter todas as respostas.', 'Cuida de quem ainda trabalha, de quem vigia e de quem procura abrigo ou companhia. Que possamos oferecer e receber apoio. Acompanha meu repouso e renova minha disposição para viver o próximo dia com atenção, responsabilidade e esperança.', 'Dar lugar ao descanso', 'Ao encerrar o dia, você pode anotar uma tarefa para amanhã e reconhecer um gesto bom de hoje.', 'O que você pode deixar preparado para descansar com mais tranquilidade?'],
];

export const DAILY_PRAYERS = Object.freeze(entries.map(([title, greeting, first, second, reflectionTitle, reflection, prompt], index) => Object.freeze({
  id: `prayer-v1-${String(index + 1).padStart(2, '0')}`,
  title,
  paragraphs: Object.freeze([greeting, first, second, 'Em nome de Jesus, amém.']),
  reflectionTitle, reflection, prompt,
})));

function validDay(value) {
  return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value)
    && Number.isFinite(Date.parse(`${value}T00:00:00Z`))
    && new Date(`${value}T00:00:00Z`).toISOString().slice(0, 10) === value;
}

export function prayerDayInBrazil(now = new Date()) {
  if (!(now instanceof Date) || !Number.isFinite(now.getTime())) throw new TypeError('Data inválida.');
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {
    timeZone: PRAYER_TIME_ZONE, year: 'numeric', month: '2-digit', day: '2-digit',
  }).formatToParts(now).map(({ type, value }) => [type, value]));
  return `${parts.year}-${parts.month}-${parts.day}`;
}

export function getDailyPrayer(day) {
  if (!validDay(day) || day < PRAYER_COLLECTION_START) throw new RangeError('Edição de oração indisponível.');
  const offset = Math.round((Date.parse(`${day}T00:00:00Z`) - Date.parse(`${PRAYER_COLLECTION_START}T00:00:00Z`)) / 86400000);
  return {
    ...DAILY_PRAYERS[offset % DAILY_PRAYERS.length], day,
    edition: new Intl.DateTimeFormat('pt-BR', { timeZone: 'UTC', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${day}T12:00:00Z`)),
  };
}

const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function replaceSlot(template, slot, html) {
  const start = `<!-- prayer:${slot}:start -->`, end = `<!-- prayer:${slot}:end -->`;
  const from = template.indexOf(start), to = template.indexOf(end);
  if (from < 0 || to < from || template.indexOf(start, from + start.length) >= 0 || template.indexOf(end, to + end.length) >= 0) {
    throw new Error(`Modelo de oração incompleto: ${slot}.`);
  }
  return `${template.slice(0, from + start.length)}${html}${template.slice(to)}`;
}

export function renderDailyPrayer(template, prayer) {
  let html = replaceSlot(String(template), 'edition', `<time id="prayerEdition" datetime="${escapeHtml(prayer.day)}">${escapeHtml(prayer.edition)}</time>`);
  html = replaceSlot(html, 'text', `<h2 id="prayerTitle">${escapeHtml(prayer.title)}</h2>\n${prayer.paragraphs.map((text, i) => `<p${i === 0 ? ' class="salutation"' : i === prayer.paragraphs.length - 1 ? ' class="prayer-ending"' : ''} data-prayer-paragraph>${escapeHtml(text)}</p>`).join('\n')}`);
  html = replaceSlot(html, 'reflection', `<h2 id="reflectionTitle">${escapeHtml(prayer.reflectionTitle)}</h2><p>${escapeHtml(prayer.reflection)}</p><p class="reflection-prompt">${escapeHtml(prayer.prompt)}</p>`);
  return replaceSlot(html, 'footer-edition', escapeHtml(prayer.edition));
}

export function createPrayerDailyHandler({ readTemplate, now = () => new Date() } = {}) {
  if (typeof readTemplate !== 'function' || typeof now !== 'function') throw new TypeError('Leitura do modelo e relógio são necessários.');
  return (req, res, next) => {
    try {
      const today = prayerDayInBrazil(now());
      const day = req.query?.dia === undefined ? today : req.query.dia;
      res.set('Cache-Control', 'no-store');
      if (!validDay(day) || day < PRAYER_COLLECTION_START || day > today) {
        return res.status(400).type('html').send('<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edição indisponível</title><main><h1>Esta edição não está disponível.</h1><p>Escolha a oração de hoje para continuar.</p><a href="/oracao-do-dia#oracao">Ler a oração de hoje</a></main></html>');
      }
      return res.type('html').send(renderDailyPrayer(readTemplate(), getDailyPrayer(day)));
    } catch (error) {
      return next(error);
    }
  };
}
